### ISSUE TITLE
2セット効果を選択したときにcleanup modeがうまく動作しない

### ISSUE THREAD

**Issue by Karashina** [Karashina/AutoWeaponCalc#8]
cleanup mode の存在意義が怪しいので別の処理で代用する

**Comment by iwonder118** [comment]
下記のコミットの実装で認識合いますか？
https://github.com/Karashina/AutoWeaponCalc/commit/54c6685f988440c700231c6511b81d69c619adde

**Comment by Karashina** [comment]
OKです！Closedにします
